services:
  global_mysql:
    image: mysql:8.0
    container_name: global_mysql
    expose:
      - "3306"
    env_file:
      - _env/${STAGE}/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - shared-global-network

  global_pma:
    image: phpmyadmin:apache
    container_name: global_pma
    expose:
      - "80"
    depends_on:
      - global_mysql
    environment:
      PMA_HOST: global_mysql
    env_file:
      - _env/${STAGE}/mysql.env
    networks:
      - shared-global-network

  global_nginx_proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: global_nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_pm_data:/data
      - nginx_pm_letsencrypt:/etc/letsencrypt
    networks:
      - shared-global-network

  global_minio:
    image: minio/minio
    container_name: global_minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    env_file:
      - _env/${STAGE}/minio.env
    volumes:
      - miniodata:/data
    networks:
      - shared-global-network
    expose:
      - "9001"
      - "9000"

volumes:
  mysql_data :
    external: true
    name: global_apps_mysql_data
  miniodata:
  nginx_pm_data:
  nginx_pm_letsencrypt:

networks:
  shared-global-network:
    external: true
    